version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn global add codecov
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:coverage
      - run: codecov


